server:
  port: 8082
  mode: "dev"
postgresql:
  username: postgres
  password: "1234567890"
  host: localhost
  port: 5432
  dbname : shopdevgov2
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
security:
  jwt:
    secret: quang23@##@@
logger:
  file_name: "./storages/logger/logv1.001.log"
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true
  loglevel:  debug
redis:
  host: localhost
  port: 6381
  password: 
  db: 0
  pool_size: 10
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SERCERT_KEY: "abahbshbhzbxhzbxh@@#s"